-- H2 schema for bookstore (compatible with H2 2.x)
-- Note: SET MODE MySQL enables ON UPDATE CURRENT_TIMESTAMP for updated_at auto-update behavior
SET MODE MySQL;

-- Optional: create and use a schema
CREATE SCHEMA IF NOT EXISTS PUBLIC;
SET SCHEMA PUBLIC;

-- ---------------------------
-- Table: users
-- ---------------------------
CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255),
  username VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT uk_users_email UNIQUE (email)
);

-- ---------------------------
-- Table: roles
-- ---------------------------
CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT uk_roles_name UNIQUE (name)
);

-- ---------------------------
-- Table: categories
-- ---------------------------
CREATE TABLE IF NOT EXISTS categories (
  category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT uk_categories_name UNIQUE (name)
);

-- ---------------------------
-- Table: books
-- ---------------------------
CREATE TABLE IF NOT EXISTS books (
  book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author VARCHAR(255),
  cover_image VARCHAR(255),
  description CLOB,
  isbn VARCHAR(255),
  price DECIMAL(38,2),
  published_date DATE,
  publisher VARCHAR(255),
  stock INT,
  title VARCHAR(255) NOT NULL
);

-- ---------------------------
-- Table: orders
-- ---------------------------
CREATE TABLE IF NOT EXISTS orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6),
  payment_method VARCHAR(255),
  shipping_address VARCHAR(255),
  status VARCHAR(255),
  total_amount DECIMAL(38,2),
  user_id BIGINT NOT NULL,
  CONSTRAINT fk_orders_user
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- ---------------------------
-- Table: order_items
-- ---------------------------
CREATE TABLE IF NOT EXISTS order_items (
  order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  price_at_purchase DECIMAL(38,2),
  quantity INT,
  book_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  CONSTRAINT fk_order_items_book
    FOREIGN KEY (book_id) REFERENCES books(book_id),
  CONSTRAINT fk_order_items_order
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- ---------------------------
-- Table: book_categories (junction)
-- ---------------------------
CREATE TABLE IF NOT EXISTS book_categories (
  book_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  created_at TIMESTAMP(6),
  priority INT,
  PRIMARY KEY (book_id, category_id),
  CONSTRAINT fk_book_categories_book
    FOREIGN KEY (book_id) REFERENCES books(book_id),
  CONSTRAINT fk_book_categories_category
    FOREIGN KEY (category_id) REFERENCES categories(category_id)
);